[package]
name = "funxscreen"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.30.11"
wry = "0.52.0"
image = "0.25.6"
http = "1.3.1"
http-range = "0.1.5"
xrutes = "0.1.2"

