[package]
name = "funxscreen"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.164"
serde_json = "1.0.99"
tokio = { version = "1.37.0", features = ["full"] }
http-range = "0.1.5"
base64 = "0.22.1"
serde_derive = "1.0.219"
serialport = "4.7.1"
rosc = "0.6"
image = "0.25.6"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
